package view;

import Utility.Uhelper;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import model.Calculate;
import model.BillingDetail;
import service.CalculateService;
import service.impl.CalculateImpl;

public class CalculateForm extends javax.swing.JFrame {

    private LoginForm dnf = new LoginForm();
    private CalculateService cs = new CalculateImpl();
    private DefaultTableModel model = new DefaultTableModel();
    private int index;
    private int stt;
    private int sum_money;

    /**
     * Creates new form Calculate
     */
    public CalculateForm() {
        initComponents();
        setLocationRelativeTo(null);
        
        model = (DefaultTableModel) tblCalculate.getModel();
        
        stt = 1;
        index = -1;
        lblUsername.setText("NV: "+cs.readFile());
        getTime();

        String listModel = cs.deleteCalculateTable();
        loadData(cs.getAll());
        setTotalMax();
        setTotalMin();
    }

    private void loadData(ArrayList<Calculate> lstCalculate) {
        model.setRowCount(0);
        stt = 1;
        for (Calculate c : lstCalculate) {
            model.addRow(new Object[]{
                stt++,
                c.getId_product(),
                c.getName_product(),
                c.getQuantity(),
                c.getUnit_price(),
                c.getTotal()});
        }
    }

    private void setTotalMin() {
        BillingDetail c = cs.getMinTotal();
        if (c == null) {
            lblIdPro1.setText("");
            lblNamePro1.setText("");
        } else {
            lblIdPro1.setText("MSP: "+c.getId_product());
            lblNamePro1.setText(c.getName_product());
        }
    }

    private void setTotalMax() {
        BillingDetail c = cs.getMaxTotal();
        if (c == null) {
            lblIdPro2.setText("");
            lblNamePro2.setText("");
        } else {
            lblIdPro2.setText("MSP: "+c.getId_product());
            lblNamePro2.setText(c.getName_product());
        }
    }

    private int total(ArrayList<Calculate> lstCalculateModels) {
        lstCalculateModels = cs.getAll();
        sum_money = 0;

        for (int i = 0; i < lstCalculateModels.size(); i++) {
            sum_money += lstCalculateModels.get(i).getTotal();
        }

        return sum_money;
    }

    private void calculte_money() {

        lblTotal.setText("" + total(cs.getAll()));
        lblVAT.setText("" + (total(cs.getAll()) * 0.1));
        lblTotalWithVAT.setText("" + (total(cs.getAll()) + (total(cs.getAll()) * 0.1)));

    }

    private void showDetail() {

        txtIdPro.setText(cs.getAll().get(index).getId_product());
        txtNamePro.setText(cs.getAll().get(index).getName_product());
        txtQuantity.setText("" + cs.getAll().get(index).getQuantity());
        txtPrice.setText("" + cs.getAll().get(index).getUnit_price());

        tblCalculate.setRowSelectionInterval(index, index);
    }

    private void clearForm() {
        txtIdPro.setText("");
        txtPrice.setText("");
        txtNamePro.setText("");
        txtQuantity.setText("");
        txtFindInput.setText("");

        String listModel = cs.deleteCalculateTable();
        loadData(cs.getAll());
        stt = 1;
        
        lblTotal.setText("0");
        lblVAT.setText("0");
        lblTotalWithVAT.setText("0");
        lblCustomerReturnMoney.setText("0");
        txtCustomerPay.setText("0");
    }
    
    private void getTime(){
    Thread t = new Thread() {
            @Override
            public void run() {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/YYYY hh:mm");
                while (true) {
                    try {
                        Date d = new Date();
                        lblTime.setText(sdf.format(d));
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        break;
                    }
                }
            }
        };
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblNamePro2 = new javax.swing.JLabel();
        lblNamePro1 = new javax.swing.JLabel();
        lblIdPro1 = new javax.swing.JLabel();
        lblIdPro2 = new javax.swing.JLabel();
        btnFind = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtIdPro = new javax.swing.JTextField();
        txtNamePro = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtFindInput = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCalculate = new javax.swing.JTable();
        jTextField8 = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblVAT = new javax.swing.JLabel();
        lblTotalWithVAT = new javax.swing.JLabel();
        lblCustomerReturnMoney = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblIconCart = new javax.swing.JLabel();
        txtCustomerPay = new javax.swing.JTextField();
        btnTinhTien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1412));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tính tiền");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 180, 30);

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUsername.setText("NV:Nguyễn Văn A");
        jPanel1.add(lblUsername);
        lblUsername.setBounds(1060, 0, 290, 30);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(0, 32, 1520, 1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 71, 72));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Kết quả");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 150, 32);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 71, 72)));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Doanh thu nhỏ nhất :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 30, 200, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Doanh thu lớn nhất :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 200, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(140, 40, 210, 70);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 71, 72)));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 0, 150, 0);

        lblNamePro2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel3.add(lblNamePro2);
        lblNamePro2.setBounds(170, 30, 190, 30);

        lblNamePro1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel3.add(lblNamePro1);
        lblNamePro1.setBounds(170, 0, 190, 30);

        lblIdPro1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel3.add(lblIdPro1);
        lblIdPro1.setBounds(20, 0, 100, 30);

        lblIdPro2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel3.add(lblIdPro2);
        lblIdPro2.setBounds(20, 30, 100, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(360, 40, 380, 70);

        btnFind.setBackground(new java.awt.Color(245, 71, 72));
        btnFind.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        btnFind.setForeground(new java.awt.Color(255, 255, 255));
        btnFind.setText("Tìm kiếm");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        jPanel1.add(btnFind);
        btnFind.setBounds(1040, 50, 150, 50);

        jTextField2.setBackground(new java.awt.Color(245, 71, 72));
        jTextField2.setText("jTextField2");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(0, 122, 1520, 1);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Mã sản phẩm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 140, 190, 27);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Tên sản phẩm");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 180, 190, 27);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Số lượng");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 220, 130, 27);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Đơn giá");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 260, 110, 40);

        txtPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 71, 72)));
        txtPrice.setRequestFocusEnabled(false);
        jPanel1.add(txtPrice);
        txtPrice.setBounds(370, 260, 480, 30);

        txtIdPro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 71, 72)));
        txtIdPro.setRequestFocusEnabled(false);
        jPanel1.add(txtIdPro);
        txtIdPro.setBounds(370, 140, 480, 30);

        txtNamePro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 71, 72)));
        txtNamePro.setRequestFocusEnabled(false);
        jPanel1.add(txtNamePro);
        txtNamePro.setBounds(370, 180, 480, 30);

        txtQuantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 71, 72)));
        jPanel1.add(txtQuantity);
        txtQuantity.setBounds(370, 220, 480, 30);

        txtFindInput.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFindInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 71, 72)));
        jPanel1.add(txtFindInput);
        txtFindInput.setBounds(750, 50, 290, 50);

        btnAdd.setBackground(new java.awt.Color(245, 71, 72));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);
        btnAdd.setBounds(950, 170, 120, 40);

        btnUpdate.setBackground(new java.awt.Color(245, 71, 72));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);
        btnUpdate.setBounds(1150, 170, 120, 40);

        btnDelete.setBackground(new java.awt.Color(245, 71, 72));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);
        btnDelete.setBounds(950, 240, 120, 40);

        btnNew.setBackground(new java.awt.Color(245, 71, 72));
        btnNew.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setText("Làm mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel1.add(btnNew);
        btnNew.setBounds(1150, 240, 120, 40);

        btnLogOut.setBackground(new java.awt.Color(245, 71, 72));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Đăng xuất");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut);
        btnLogOut.setBounds(1220, 650, 120, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Thời gian");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(320, 630, 90, 22);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Tiền trả lại");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(320, 600, 90, 22);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("Tiền khách trả");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(320, 570, 110, 22);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("Tổng tiền thanh toán");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(320, 540, 160, 22);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setText("Thuế VAT(10%)");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(320, 510, 120, 22);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setText("Tổng tiền");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(320, 480, 70, 30);

        tblCalculate.setBackground(new java.awt.Color(255, 204, 204));
        tblCalculate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblCalculate.setForeground(new java.awt.Color(51, 51, 51));
        tblCalculate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCalculate.setGridColor(new java.awt.Color(255, 238, 238));
        tblCalculate.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tblCalculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCalculateMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCalculate);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(90, 320, 1180, 140);

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(245, 71, 72));
        jTextField8.setText("jTextField8");
        jPanel1.add(jTextField8);
        jTextField8.setBounds(0, 470, 1480, 1);

        btnExit.setBackground(new java.awt.Color(245, 71, 72));
        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(10, 650, 120, 40);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTotal.setText("0");
        jPanel1.add(lblTotal);
        lblTotal.setBounds(820, 480, 120, 22);

        lblVAT.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblVAT.setText("0");
        jPanel1.add(lblVAT);
        lblVAT.setBounds(820, 510, 130, 22);

        lblTotalWithVAT.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTotalWithVAT.setText("0");
        jPanel1.add(lblTotalWithVAT);
        lblTotalWithVAT.setBounds(820, 540, 130, 22);

        lblCustomerReturnMoney.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCustomerReturnMoney.setText("0");
        jPanel1.add(lblCustomerReturnMoney);
        lblCustomerReturnMoney.setBounds(820, 600, 130, 22);

        lblTime.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTime.setText("09:12 16/03/2023");
        jPanel1.add(lblTime);
        lblTime.setBounds(820, 630, 270, 22);

        lblIconCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_xe_đẩy.jpg"))); // NOI18N
        jPanel1.add(lblIconCart);
        lblIconCart.setBounds(1270, 50, 60, 60);

        txtCustomerPay.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtCustomerPay.setText("0");
        txtCustomerPay.setBorder(null);
        jPanel1.add(txtCustomerPay);
        txtCustomerPay.setBounds(820, 570, 120, 22);

        btnTinhTien.setBackground(new java.awt.Color(245, 71, 72));
        btnTinhTien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnTinhTien.setForeground(new java.awt.Color(255, 255, 255));
        btnTinhTien.setText("Tính tiền");
        btnTinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTienActionPerformed(evt);
            }
        });
        jPanel1.add(btnTinhTien);
        btnTinhTien.setBounds(1220, 590, 120, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTienActionPerformed
        if (txtCustomerPay.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn vui lòng nhập tiền khách đưa !");
            return;
        }
        double money_customerPay = Double.parseDouble(txtCustomerPay.getText());
        if (money_customerPay < Double.parseDouble(lblTotalWithVAT.getText())) {
            JOptionPane.showMessageDialog(this, "Quý khách vui lòng thanh toán đầy đủ hóa đơn !");
            return;
        }
        lblCustomerReturnMoney.setText("" + (money_customerPay - Double.parseDouble(lblTotalWithVAT.getText())));
        LocalDateTime current = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofLocalizedDateTime(FormatStyle.MEDIUM);
        String formatted = current.format(formatter);
        lblTime.setText(formatted);
    }//GEN-LAST:event_btnTinhTienActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void tblCalculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCalculateMouseClicked
        index = tblCalculate.getSelectedRow();
        showDetail();

    }//GEN-LAST:event_tblCalculateMouseClicked

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        clearForm();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        if (Uhelper.checkNull(txtQuantity, "Bạn vui lòng nhập số lượng !")) {
            return;
        }

        try {
            Integer.parseInt(txtQuantity.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bạn vui lòng nhập số !");
            return;
        }
        String id_product = txtIdPro.getText();
        String name_product = txtNamePro.getText();
        int quantity = Integer.parseInt(txtQuantity.getText());
        int price = Integer.parseInt(txtPrice.getText());
        int total = quantity * price;

        
        Calculate c = new Calculate(id_product, name_product, quantity, price, total);

        String result = cs.addNew(c);
        
        
        BillingDetail bd = new BillingDetail(id_product, name_product, quantity, price, total);
        String addModel = cs.addNewModel(bd);

        loadData(cs.getAll());
        
        if (cs.getAllModel().size() == 1) {
            setTotalMax();
        } else {
            setTotalMin();
            setTotalMax();
        }
        calculte_money();
         String update = cs.getTblQuantityAfterCalculates(c.getId_product());
         
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String id_product = txtFindInput.getText();

        Calculate c = cs.getById(id_product);
        if (c == null) {
            JOptionPane.showMessageDialog(this, "Sai mã sản phẩm!");
            return;
        } else {
            txtIdPro.setText(id_product);
            txtNamePro.setText(c.getName_product());
            txtQuantity.setText("");
            txtPrice.setText("" + c.getUnit_price());
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        index = tblCalculate.getSelectedRow();
        
        Calculate c = cs.getAll().get(index);
        
        String rollBack =  cs.rollBack(c.getId_product());
        
        String id_product = txtIdPro.getText();
        String name_product = txtNamePro.getText();
        int quantity = Integer.parseInt(txtQuantity.getText());
        int price = Integer.parseInt(txtPrice.getText());
        int total = quantity * price;

        c = new Calculate(id_product, name_product, quantity, price, total);
        
        String deleteBillingDetail =  cs.deleteBilling(c.getId_product());
  
        BillingDetail bd = new BillingDetail(id_product, name_product, quantity, price, total);
        String result = cs.update(id_product, c);
        
        JOptionPane.showMessageDialog(this, result);
        
        String addModel = cs.addNewModel(bd);
        
        loadData(cs.getAll());
        
        if (cs.getAllModel().size() == 1) {
            setTotalMax();
        } else {
            setTotalMin();
            setTotalMax();
        }

        calculte_money();
        String update = cs.getTblQuantityAfterCalculates(c.getId_product());
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        index = tblCalculate.getSelectedRow();
        if(index == -1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm muốn xóa!");
            return;
        }
        Calculate c = cs.getAll().get(index);
        
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?");
        if(hoi != JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
            return;
        }
        String rollBack =  cs.rollBack(c.getId_product());
        String delete = cs.delete(c.getId_product());
        String deleteBillingDetail =  cs.deleteBilling(c.getId_product());

        txtIdPro.setText("");
        txtPrice.setText("");
        txtNamePro.setText("");
        txtQuantity.setText("");
        txtFindInput.setText("");
        tblCalculate.clearSelection();
        
        loadData(cs.getAll());
        if (cs.getAll().size() == 1) {
            setTotalMax();
        } else {
            setTotalMin();
            setTotalMax();
        }
        calculte_money();
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnTinhTien;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblCustomerReturnMoney;
    private javax.swing.JLabel lblIconCart;
    private javax.swing.JLabel lblIdPro1;
    private javax.swing.JLabel lblIdPro2;
    private javax.swing.JLabel lblNamePro1;
    private javax.swing.JLabel lblNamePro2;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalWithVAT;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblVAT;
    private javax.swing.JTable tblCalculate;
    private javax.swing.JTextField txtCustomerPay;
    private javax.swing.JTextField txtFindInput;
    private javax.swing.JTextField txtIdPro;
    private javax.swing.JTextField txtNamePro;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

}
