package view;

import Utility.Uhelper;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import model.Customer;
import service.DangNhapService;
import service.impl.DangNhapImpl;

public class LoginForm extends javax.swing.JFrame {

    private DangNhapService dangNhapService = new DangNhapImpl();

    public LoginForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        rdoCaculate = new javax.swing.JRadioButton();
        rdoProductManagement = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnIconExit = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1140, 860));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1140, 860));
        jPanel1.setLayout(null);

        btnLogin.setBackground(new java.awt.Color(245, 71, 72));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Đăng nhập");
        btnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 71, 72)));
        btnLogin.setBorderPainted(false);
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setPreferredSize(new java.awt.Dimension(281, 56));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin);
        btnLogin.setBounds(410, 540, 281, 56);

        rdoCaculate.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoCaculate);
        rdoCaculate.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        rdoCaculate.setText("Thanh toán");
        rdoCaculate.setPreferredSize(new java.awt.Dimension(148, 50));
        jPanel1.add(rdoCaculate);
        rdoCaculate.setBounds(280, 430, 230, 50);

        rdoProductManagement.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoProductManagement);
        rdoProductManagement.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        rdoProductManagement.setText("Quản lý sản phẩm");
        rdoProductManagement.setPreferredSize(new java.awt.Dimension(232, 50));
        jPanel1.add(rdoProductManagement);
        rdoProductManagement.setBounds(600, 430, 232, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mật khẩu");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 320, 125, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tài khoản");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 210, 125, 50);

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 71, 72), 3));
        jPanel1.add(txtUsername);
        txtUsername.setBounds(350, 200, 440, 60);

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 71, 72), 3));
        jPanel1.add(txtPassword);
        txtPassword.setBounds(350, 310, 440, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 45)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đăng nhập");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(438, 75, 257, 60);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Đăng nhập");
        jLabel4.setPreferredSize(new java.awt.Dimension(182, 41));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(24, 7, 182, 41);

        btnIconExit.setBorder(null);
        btnIconExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnIconExit);
        btnIconExit.setBounds(0, 0, 0, 0);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(245, 71, 72));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(0, 55, 1140, 2);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon thoát.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(1079, 7, 40, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (Uhelper.checkNull(txtUsername, "Bạn vui lòng nhập username")) {
            return;
        }

        if (Uhelper.checkNull(txtPassword, "Bạn vui lòng nhập password")) {
            return;
        }

        String username = txtUsername.getText();
        String password = String.valueOf(txtPassword.getPassword());

        String chucNang;
        if (rdoCaculate.isSelected()) {
            chucNang = "Thanh toán";
        } else {
            chucNang = "Quản lý sản phẩm";
        }
        String result;
        Customer cus = dangNhapService.loginCustomer(username, password);
        if (cus == null) {
            result = "Đăng nhập thất bại!";
            JOptionPane.showMessageDialog(this, result);
        } else {
            result = "Đăng nhập thành công.";
            dangNhapService.writeFile(username);
        }
        
        if (chucNang.equalsIgnoreCase("Thanh toán") && result.equalsIgnoreCase("Đăng nhập thành công.")) {
            CalculateForm tt = new CalculateForm();
            tt.setVisible(true);
            this.dispose();

        } else if (chucNang.equalsIgnoreCase("Quản lý sản phẩm") && result.equalsIgnoreCase("Đăng nhập thành công.")) {
            ManagementProductForm qlsp = new ManagementProductForm();
            qlsp.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnIconExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnIconExitActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnIconExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rdoCaculate;
    private javax.swing.JRadioButton rdoProductManagement;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
